### ISSUE TITLE
Clarification Needed: Which JSON File to Import for Firebase Setup?

### ISSUE THREAD

**Issue by btentimishov** [GetStream/ai-chat-android#21]
In the README, the sentence:

> "Next, set up the Firebase Realtime Database in your Firebase dashboard. Once that's done, you can import the JSON file like the image below:"

is unclear. It doesn't specify which JSON file needs to be imported. Could you clarify whether this is a sample file from the repository or something the user needs to create? Adding details or a link would be very helpful.

Thanks!

**Comment by skydoves** [comment]
Hey @btentimishov, sorry for the unclear docs. That step should be removed since this repository doesn't need to be set up by importing the JSON file. Thanks!
